KP1         add contrast -1               # Video > Decrease Contrast
KP4         add contrast 1                # Video > Increase Contrast
KP2         add brightness -1             # Video > Decrease Brightness
KP3         add brightness 1              # Video > Increase Brightness
KP5         add gamma -1                  # Video > Decrease Gamma
KP6         add gamma 1                   # Video > Increase Gamma
KP8         add saturation -1             # Video > Decrease Saturation
KP9         add saturation 1              # Video > Increase Saturation
\           async screenshot              # Video > Take Screenshot
n           script-message-to mpvnet cycle-subtitles  # Subtitle > Next Track
#--- Mouse / UI ---
MBTN_LEFT   cycle pause;script-message-to uosc flash-pause-indicator
TAB         script-message-to uosc toggle-ui
MBTN_LEFT   script-binding evafast/speedup  # @press
MBTN_LEFT   script-binding evafast/slowdown  # @release

#--- Playlist ---
;           playlist-prev
'           playlist-next

#--- Video ---
Alt+d       cycle deband
Ctrl+d      script-binding autodeint/autodeint
Alt+s       script-message-to uosc show-submenu-blurred "Video > Shaders"

#--- Menus ---
Alt+a       script-message-to uosc show-submenu-blurred "Open"
Alt+z       script-message-to uosc show-submenu-blurred "Audio"
Alt+x       script-message-to uosc show-submenu-blurred "Subtitles"

#--- Open ---
b           script-binding uosc/open-file
h           script-binding memo-history

#--- Video Filters / Profiles ---
g           cycle interpolation
Alt+v       vf toggle deblock=filter=weak:block=4
n           change-list glsl-shaders toggle ~~/shaders/nlmeans_luma.glsl

Ctrl+1      apply-profile FSRCNNX;show-text "Profile: FSRCNNX"
Ctrl+2      apply-profile FSRCNNX+;show-text "Profile: FSRCNNX+"
Ctrl+3      apply-profile Ravu-Zoom;show-text "Profile: Ravu-Zoom"
Ctrl+4      apply-profile Ani4k;show-text "Profile: Ani4k"
Ctrl+5      apply-profile AniSD;show-text "Profile: AniSD"
Ctrl+6      apply-profile Anime4K;show-text "Profile: Anime4K"
Ctrl+7      apply-profile NNEDI3;show-text "Profile: NNEDI3"
Ctrl+8      apply-profile NNEDI3+;show-text "Profile: NNEDI3+"

c           change-list glsl-shaders clr all

#--- Audio ---
F1          af toggle "lavfi=[loudnorm=I=-14:TP=-3:LRA=4]" ; show-text "${af}"
b           cycle audio                   # next audio

#--- Subtitles ---
s           cycle sub-visibility
v           cycle sub                     # next subtitle
y           script-binding uosc/load-subtitles
Y           script-binding uosc/subtitles
Alt+j       add sub-scale +0.05
Alt+k       add sub-scale -0.05
z           add sub-delay -0.1
x           add sub-delay  0.1

#--- Tools ---
/           script-binding console/enable

#--- Window ---
a           cycle window-minimized
q           quit-watch-later


Ctrl+s async screenshot window