# E-INK Monochrome (Extended Palette)

background            #121212
foreground            #e0e0e0
cursor                #e0e0e0
cursor_text_color     #121212
selection_background  #444444
selection_foreground  #e0e0e0

# URL underline color when hovering
url_color             #b9bdc2

# Kitty window border colors
active_border_color     #e0e0e0
inactive_border_color   #2a2a2a
bell_border_color       #b9bdc2

# OS Window titlebar colors
wayland_titlebar_color system

# Tab bar colors
active_tab_foreground   #121212
active_tab_background   #e0e0e0
inactive_tab_foreground #888c94
inactive_tab_background #1c1c1c
tab_bar_background      #121212

# THE 16 TERMINAL COLORS

# black (bg1 and grey0)
color0 #1c1c1c
color8 #555a5b

# red (locked to fg)
color1 #e0e0e0
color9 #e0e0e0

# green (locked to fg)
color2 #e0e0e0
color10 #e0e0e0

# yellow (locked to fg)
color3 #e0e0e0
color11 #e0e0e0

# blue (locked to fg)
color4 #e0e0e0
color12 #e0e0e0

# magenta (locked to fg)
color5 #e0e0e0
color13 #e0e0e0

# cyan (locked to fg)
color6 #e0e0e0
color14 #e0e0e0

# white (grey1 and grey2)
color7 #888c94
color15 #b9bdc2
