general {
    hide_cursor = false
    border_size = 0
}

background {
    monitor =
    path = screenshot

    blur_passes = 4
    blur_size = 8
    noise = 0.0
    contrast = 1.15
    brightness = 0.82
    vibrancy = 0.2
}

label {
    monitor =

    text = cmd[update:1000] date +"%H:%M"

    color = rgb(ffffff)
    font_size = 82
    font_family = Inter

    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] date +"%A, %d %B"

    color = rgb(cfcfcf)
    font_size = 22
    font_family = Inter

    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 320, 52

    outline_thickness = 0

    outer_color = rgba(00000000)
    inner_color = rgba(202020bb)

    font_color = rgb(ffffff)
    font_family = Inter
    font_size = 18

    fade_on_empty = false
    placeholder_text = Password

    hide_input = false

    rounding = 12

    check_color = rgb(7dcfff)
    fail_color = rgb(ff6b6b)

    position = 0, -40
    halign = center
    valign = center
}